packages/actor-init-sparql/package.json
packages/actor-query-operation-bgp-left-deep-smallest-sort/README.md
packages/actor-query-operation-bgp-left-deep-smallest-sort/components/Actor/QueryOperation/BgpLeftDeepSmallestSort.jsonld
packages/actor-query-operation-bgp-left-deep-smallest-sort/components/components.jsonld
packages/actor-query-operation-bgp-left-deep-smallest-sort/components/context.jsonld
packages/actor-query-operation-bgp-left-deep-smallest-sort/index.ts
packages/actor-query-operation-bgp-left-deep-smallest-sort/lib/ActorQueryOperationBgpLeftDeepSmallestSort.ts
packages/actor-query-operation-bgp-left-deep-smallest-sort/package.json
packages/actor-query-operation-bgp-left-deep-smallest-sort/test/ActorQueryOperationBgpLeftDeepSmallestSort-test.ts
packages/actor-query-operation-bgp-left-deep-smallest-sort/test/tsconfig.json
packages/actor-query-operation-bgp-left-deep-smallest-sort/test/tslint.json
packages/actor-query-operation-bgp-left-deep-smallest-sort/tsconfig.json
packages/actor-query-operation-bgp-left-deep-smallest-sort/tslint.json

As originally introduced in #106, and similar to #102, this is a variant of the left-deep-smallest actor with the only difference that it also sorts the remaining patterns by increasing count.
Results show that this actor only in some cases outperforms the default actor, so we should keep the other actor as default. In future work, we should add a mediator that intelligently identifies the cases in which the other actor is sub-optimal, and chooses another actor.

Add BGP left-deep-smallest-sort Query Operation Actor

---

packages/actor-init-sparql/config/config-default.json
packages/actor-sparql-serialize-stats/README.md
packages/actor-sparql-serialize-stats/components/Actor/SparqlSerialize/Stats.jsonld
packages/actor-sparql-serialize-stats/components/components.jsonld
packages/actor-sparql-serialize-stats/components/context.jsonld
packages/actor-sparql-serialize-stats/index.ts
packages/actor-sparql-serialize-stats/lib/ActorSparqlSerializeStats.ts
packages/actor-sparql-serialize-stats/package.json
packages/actor-sparql-serialize-stats/test/ActorSparqlSerializeStats-test.ts
packages/actor-sparql-serialize-stats/test/tsconfig.json
packages/actor-sparql-serialize-stats/test/tslint.json
packages/actor-sparql-serialize-stats/tsconfig.json
packages/actor-sparql-serialize-stats/tslint.json

This PR adds a serializer for evaluation or debugging purposes. 
TODO: implement the per-result request count, when the right method way to obtain that number is found.

Added stats serializer

---

packages/actor-init-sparql/config/config-default.json
packages/actor-rdf-source-identifier-file-content-type/components/Actor/RdfSourceIdentifier/FileContentType.jsonld
packages/actor-rdf-source-identifier-file-content-type/lib/ActorRdfSourceIdentifierFileContentType.ts
packages/actor-rdf-source-identifier-file-content-type/package.json
packages/actor-rdf-source-identifier-hypermedia-qpf/components/Actor/RdfSourceIdentifier/HypermediaQpf.jsonld
packages/actor-rdf-source-identifier-hypermedia-qpf/lib/ActorRdfSourceIdentifierHypermediaQpf.ts
packages/actor-rdf-source-identifier-hypermedia-qpf/package.json
packages/actor-rdf-source-identifier-sparql/components/Actor/RdfSourceIdentifier/Sparql.jsonld
packages/actor-rdf-source-identifier-sparql/lib/ActorRdfSourceIdentifierSparql.ts
packages/actor-rdf-source-identifier-sparql/package.json
packages/bus-rdf-source-identifier/components/Actor/RdfSourceIdentifier.jsonld
packages/bus-rdf-source-identifier/lib/ActorRdfSourceIdentifier.ts
packages/bus-rdf-source-identifier/package.json
packages/mediator-number/components/Mediator/Number.jsonld
packages/mediator-number/components/context.jsonld
packages/mediator-number/lib/MediatorNumber.ts
packages/mediator-number/test/MediatorNumber-test.ts
packages/mediatortype-priority/README.md
packages/mediatortype-priority/index.ts
packages/mediatortype-priority/lib/MediatorTypePriority.ts
packages/mediatortype-priority/package.json
packages/mediatortype-priority/tsconfig.json
packages/mediatortype-priority/tslint.json

This makes sure that sources that match both files and hypermedia
are always recognized as hypermedia

Use order for source identifiers

---

packages/actor-init-sparql/lib/ActorInitSparql-browser.ts
packages/actor-init-sparql/package.json
packages/actor-init-sparql/test/ActorInitSparql-test.ts

This adds support for prepared statements (#161).

Allow initialBindings to be passed to query context

---

packages/core/components/ActionObserver.jsonld
packages/core/components/components.jsonld
packages/core/components/context.jsonld
packages/core/index.ts
packages/core/lib/ActionObserver.ts
packages/core/lib/Actor.ts
packages/core/lib/Bus.ts
packages/core/lib/Mediator.ts
packages/core/test/Actor-test.ts
packages/core/test/Bus-test.ts
packages/mediator-combine-pipeline/lib/MediatorCombinePipeline.ts
packages/mediator-combine-union/lib/MediatorCombineUnion.ts
packages/runner/lib/Runner.ts

This allows all Actor#run invocations to be passively observed.

Add ActionObserver

---

packages/actor-rdf-parse-jsonld/lib/ActorRdfParseJsonLd.ts

Apperantly setting the base IRI is done through the [`base`](https://github.com/digitalbazaar/jsonld.js/blob/1fae88fd856be2bdb63e3a9d71d54e848a1aafe5/lib/jsonld.js#L100) parameter and not `baseIRI` when parsing JSON using jsonld.js. This closes #342.

Fix JSON-LD parser to parse JSON with an @context attribute

---

packages/actor-query-operation-bgp-left-deep-smallest/lib/ActorQueryOperationBgpLeftDeepSmallest.ts
packages/actor-query-operation-bgp-left-deep-smallest/test/ActorQueryOperationBgpLeftDeepSmallest-test.ts
packages/actor-query-operation-bgp-single/lib/ActorQueryOperationBgpSingle.ts
packages/actor-query-operation-bgp-single/test/ActorQueryOperationBgpSingle-test.ts
packages/actor-rdf-resolve-quad-pattern-federated/lib/FederatedQuadSource.ts
packages/actor-rdf-resolve-quad-pattern-federated/test/FederatedQuadSource-test.ts
packages/bus-query-operation/lib/ActorQueryOperation.ts
yarn.lock

This is a small addition that passes around (parent) metadata to (child) query operations. This is needed for our [AMF-aware actors](https://github.com/comunica/comunica-feature-amf).

Pass parent metadata to BGP and pattern actions

---

packages/actor-init-sparql-file/README.md
packages/actor-init-sparql-file/bin/http.ts
packages/actor-init-sparql-file/package.json
packages/actor-init-sparql/index.ts
packages/actor-init-sparql/lib/HttpServiceSparqlEndpoint.ts

This allows other init actors to easily expose themselves
as a SPARQL endpoint.
Closes #184

Abstract SPARQL HTTP service

---

packages/actor-query-operation-extend/lib/ActorQueryOperationExtend.ts
packages/actor-query-operation-filter-sparqlee/lib/ActorQueryOperationFilterSparqlee.ts
packages/actor-query-operation-leftjoin-nestedloop/lib/ActorQueryOperationLeftJoinNestedLoop.ts

During the implementation of some actors I did, i had a wrong impression of how the testOperation function worked. These changes reflect the actual wanted behavior without misleading double checks that are already done in the abstract class.

Make some actors test function consistent and reflective of actual behaviour

---

package.json
packages/actor-abstract-path/package.json
packages/actor-optimize-query-operation-join-bgp/package.json
packages/actor-query-operation-extend/package.json
packages/actor-query-operation-filter-sparqlee/package.json
packages/actor-query-operation-from-quad/package.json
packages/actor-query-operation-group/package.json
packages/actor-query-operation-group/test/ActorQueryOperationGroup-test.ts
packages/actor-query-operation-leftjoin-nestedloop/package.json
packages/actor-query-operation-orderby-sparqlee/package.json
packages/actor-query-operation-path-alt/package.json
packages/actor-query-operation-path-inv/package.json
packages/actor-query-operation-path-link/package.json
packages/actor-query-operation-path-nps/package.json
packages/actor-query-operation-path-one-or-more/package.json
packages/actor-query-operation-path-seq/package.json
packages/actor-query-operation-path-zero-or-more/package.json
packages/actor-query-operation-sparql-endpoint/package.json
packages/actor-rdf-metadata-extract-sparql-service/lib/ActorRdfMetadataExtractSparqlService.ts
packages/actor-rdf-resolve-hypermedia-sparql/lib/RdfSourceSparql.ts
packages/actor-rdf-resolve-hypermedia-sparql/package.json
packages/actor-rdf-resolve-quad-pattern-file/lib/ActorRdfResolveQuadPatternFile.ts
packages/actor-rdf-resolve-quad-pattern-sparql-json/lib/ActorRdfResolveQuadPatternSparqlJson.ts
packages/actor-rdf-resolve-quad-pattern-sparql-json/package.json
packages/actor-sparql-parse-algebra/lib/ActorSparqlParseAlgebra.ts
packages/actor-sparql-parse-algebra/package.json
packages/actor-sparql-parse-algebra/test/ActorSparqlParseAlgebra-test.ts
packages/bus-optimize-query-operation/package.json
packages/bus-rdf-resolve-hypermedia-links/lib/ActorRdfResolveHypermediaLinks.ts
yarn.lock

This should make Comunica support the new sparqlalgebra.js/sparql.js. There were two tests that were being annoying where I didn't find a better solution. Feel free to improve.

Support newest Sparqlalgebra.js version

---

packages/actor-rdf-dereference-http-parse/lib/ActorRdfDereferenceHttpParseBase.ts

On several occasions, @james-martin-jd hit URLs that did not dereference, but it was hard to figure out what they were.

Clarify dereferencing error message

---

packages/actor-rdf-serialize-jsonld/lib/ActorRdfSerializeJsonLd.ts

It is `require`d in [ActorRdfSerializeJsonLd.ts:24](https://github.com/comunica/comunica/blob/master/packages/actor-rdf-serialize-jsonld/lib/ActorRdfSerializeJsonLd.ts#L24).

Add missing jsonld dependency to actor-rdf-serialize-jsonld

---

packages/actor-query-operation-bgp-left-deep-smallest-sort/package.json
packages/actor-query-operation-bgp-left-deep-smallest/package.json
packages/actor-query-operation-describe-subject/package.json
packages/actor-query-operation-minus/package.json
packages/actor-query-operation-path-alt/package.json
packages/actor-query-operation-path-one-or-more/package.json
packages/actor-query-operation-quadpattern/package.json
packages/actor-query-operation-union/package.json
packages/actor-rdf-resolve-hypermedia-qpf/package.json
packages/actor-rdf-resolve-hypermedia-sparql/package.json
packages/actor-rdf-resolve-quad-pattern-federated/lib/FederatedQuadSource.ts
packages/actor-rdf-resolve-quad-pattern-federated/package.json
packages/actor-rdf-resolve-quad-pattern-hypermedia/package.json
packages/actor-rdf-resolve-quad-pattern-sparql-json/package.json
yarn.lock

As discussed in #553, this ensures that there are no possible timing issues when acquiring the metadata in a federated situation.

Manually load sources for federated metadata

---

packages/logger-pretty/test/LoggerPretty-test.ts

This is related to #537 . I'm not gonna say it fixes it yet because there seem to be several problems there. This should fix the "Call retries were exceeded" error such as [here](https://travis-ci.org/comunica/comunica/jobs/617728041#L333) . Fortunately this error appears consistently when using the latest version of node. Not sure why though, maybe something changed to the console object and overwriting it entirely causes issues. Fun fact: the problem is also solved by removing a certain amount of tests from that file, no idea why.

Only overwrite error function for tests

---

packages/actor-rdf-resolve-hypermedia-sparql/components/Actor/RdfResolveHypermedia/Sparql.jsonld
packages/actor-rdf-resolve-hypermedia-sparql/lib/ActorRdfResolveHypermediaSparql.ts
packages/actor-rdf-resolve-hypermedia-sparql/test/ActorRdfResolveHypermediaSparql-test.ts

As discussed in #535, sources with URL ending with `/sparql` will be considered SPARQL endpoints.
Since this is a heuristic, this is disableable from the config.
Closes #535

Consider sources ending with '/sparql' as SPARQL endpoints, Closes #535

---

packages/actor-rdf-resolve-quad-pattern-federated/index.ts
packages/actor-rdf-resolve-quad-pattern-federated/lib/BlankNodeScoped.ts
packages/actor-rdf-resolve-quad-pattern-federated/lib/BlankNodeSkolemizable.ts
packages/actor-rdf-resolve-quad-pattern-federated/lib/FederatedQuadSource.ts
packages/actor-rdf-resolve-quad-pattern-federated/package.json
packages/actor-rdf-resolve-quad-pattern-federated/test/BlankNodeScoped-test.ts
packages/actor-rdf-resolve-quad-pattern-federated/test/FederatedQuadSource-test.ts

When federating over multiple sources,
the outcoming blank nodes coming from each source
will receive a distinct blank node,
so that they can not be joined across different sources,
even if they have the same blank node label.
A reverse translation also takes place for incoming queries with blank nodes,
so that these blank nodes will only match if they come from that source.
Blank nodes coming from sources will receive a .skolemized field
containing a named node.
This named node can be queried again as an IRI, and this will
be interpreted by Comunica as a blank node corresponding to the proper
source, assuming that the array of sources remains the same.
Closes #355
Required for solid/query-ldflex#34
While the implementation is quite trivial, the impact is quite major, so this deserves a …

Scope blank nodes to each federated source

---

packages/actor-rdf-metadata-extract-sparql-service/lib/ActorRdfMetadataExtractSparqlService.ts
packages/actor-rdf-metadata-extract-sparql-service/test/ActorRdfMetadataExtractSparqlService-test.ts
packages/actor-rdf-resolve-hypermedia-qpf/lib/RdfSourceQpf.ts
packages/actor-rdf-resolve-hypermedia-qpf/test/RdfSourceQpf-test.ts

This is applicable for QPF interfaces.
This fixes the problem where SPO queries over QPF
endpoints containing many triples in the non-default graph
was slow due to inefficient filtering.
Closes #623

Discover and handle default graph overrides

---

packages/actor-rdf-resolve-quad-pattern-hypermedia/lib/LinkedRdfSourcesAsyncRdfIterator.ts
packages/actor-rdf-resolve-quad-pattern-hypermedia/lib/MediatedLinkedRdfSourcesAsyncRdfIterator.ts
packages/actor-rdf-resolve-quad-pattern-hypermedia/test/LinkedRdfSourcesAsyncRdfIterator-test.ts
packages/actor-rdf-resolve-quad-pattern-hypermedia/test/MediatedLinkedRdfSourcesAsyncRdfIterator-test.ts
packages/bus-rdf-resolve-hypermedia-links/lib/ActorRdfResolveHypermediaLinks.ts

This promotes raw URL string to link objects,
where these link objects can have an optional transform function.
This is useful for actors that want links to be followed,
but only want to include some of the quads from the response.
The string-form is still allowed for backwards-compatibility.

Allow quad streams on followed links to be transformed

---

packages/actor-rdf-resolve-quad-pattern-hypermedia/lib/MediatedLinkedRdfSourcesAsyncRdfIterator.ts
packages/actor-rdf-resolve-quad-pattern-hypermedia/test/MediatedLinkedRdfSourcesAsyncRdfIterator-test.ts
packages/bus-rdf-resolve-hypermedia-links/lib/ActorRdfResolveHypermediaLinks.ts

This is needed for handling content policies during link traversal.

Allow hypermedia links to define custom context entries

---

packages/actor-abstract-bindings-hash/components/Actor/AbstractBindingsHash.jsonld
packages/actor-abstract-bindings-hash/components/Actor/AbstractFilterHash.jsonld
packages/actor-abstract-bindings-hash/components/context.jsonld
packages/actor-abstract-bindings-hash/lib/AbstractBindingsHash.ts
packages/actor-abstract-bindings-hash/lib/AbstractFilterHash.ts
packages/actor-abstract-bindings-hash/package-lock.json
packages/actor-abstract-bindings-hash/package.json
packages/actor-abstract-bindings-hash/test/AbstractBindingsHash-test.ts
packages/actor-abstract-bindings-hash/test/AbstractFilterHash-test.ts
packages/actor-query-operation-distinct-hash/README.md
packages/actor-query-operation-distinct-hash/components/Actor/QueryOperation/DistinctHash.jsonld
packages/actor-query-operation-distinct-hash/lib/ActorQueryOperationDistinctHash.ts
packages/actor-query-operation-distinct-hash/test/ActorQueryOperationDistinctHash-test.ts
packages/actor-query-operation-group/lib/GroupsState.ts
packages/actor-query-operation-reduced-hash/README.md
packages/actor-query-operation-reduced-hash/components/Actor/QueryOperation/ReducedHash.jsonld
packages/actor-query-operation-reduced-hash/lib/ActorQueryOperationReducedHash.ts
packages/actor-query-operation-reduced-hash/test/ActorQueryOperationReducedHash-test.ts
yarn.lock

This PR, which is still a WIP, introduces pure-js implementations of 
- `actor-query-operation-reduced-hash` (`actor-query-operation-reduced-purejs-hash`)
- `actor-query-operation-distinct-hash` (`actor-query-operation-distinct-purejs-hash`)
- `actor-abstract-bindings-hash` (`and actor-abstract-bindings-purejs-hash`)
The motivation behind this PR is that the `actor-abstract-bindings-hash` causes Webpack to shim the entire `crypto` module, which is not available in browsers, as it allows to use any hash that is available in Node.js. This leads to browser-side having a ton of crypto-related code for no good reason, given that everything seems to be using the default hash algorithm `sha1`. See the attached screenshot of Webpack's bundle analyzer.
I've worked on this after talking about it …

pure-js hash operators

---

packages/actor-query-operation-construct/lib/BindingsToQuadsIterator.ts
packages/actor-query-operation-construct/package.json
packages/actor-query-operation-construct/test/BindingsToQuadsIterator-test.ts
packages/actor-query-operation-extend/lib/ActorQueryOperationExtend.ts
packages/actor-query-operation-extend/package.json
packages/actor-query-operation-filter-sparqlee/lib/ActorQueryOperationFilterSparqlee.ts
packages/actor-query-operation-filter-sparqlee/package.json
packages/actor-query-operation-group/package.json
packages/actor-query-operation-leftjoin-nestedloop/lib/ActorQueryOperationLeftJoinNestedLoop.ts
packages/actor-query-operation-leftjoin-nestedloop/package.json
packages/actor-query-operation-orderby-sparqlee/lib/ActorQueryOperationOrderBySparqlee.ts
packages/actor-query-operation-orderby-sparqlee/package.json
packages/actor-query-operation-project/lib/ActorQueryOperationProject.ts
packages/actor-query-operation-project/test/ActorQueryOperationProject-test.ts
packages/bus-query-operation/lib/ActorQueryOperation.ts
packages/bus-query-operation/package.json
packages/bus-query-operation/test/ActorQueryOperation-test.ts
packages/data-factory/README.md
packages/data-factory/index.ts
packages/data-factory/lib/BlankNodeBindingsScoped.ts
packages/data-factory/test/BlankNodeBindingsScoped-test.ts

This PR (~~which depends on https://github.com/comunica/sparqlee/pull/81~~ MERGED) fixes the blank node correlation issue raised in issue https://github.com/comunica/comunica/issues/795 (and may fix other similar issues).

Fix blank node correlation (closes #795)

---

packages/actor-init-sparql/lib/ActorInitSparql-browser.ts
packages/actor-init-sparql/test/ActorInitSparql-test.ts
packages/bus-http-invalidate/lib/ActorHttpInvalidateListenable.ts
packages/bus-optimize-query-operation/lib/ActorOptimizeQueryOperation.ts
packages/bus-optimize-query-operation/package.json
packages/core/lib/Actor.ts
packages/mediator-combine-pipeline/lib/MediatorCombinePipeline.ts
packages/mediator-combine-pipeline/test/MediatorCombinePipeline-test.ts

While working on https://github.com/beautifulinteractions/node-quadstore/issues/115 I noticed that my custom optimizer actor had no `context` entry in its `action` argument. I tracked the issue to the fact that, while `MediatorCombinePipeline` does pass the output of one actor to the next one, the output of each actor is not guaranteed to have the `context` property in it and therefore only the first actor in a chain of mediated actors is guaranteed to receive the context.
This fix is backward-compatible and ensures that the properties of the original action are always preserved unless they are overwritten by one of the actors mediated over.  
Furthermore, this fix also modifies how the return value of the optimize mediator is handled. If the mediator returns a context, then the original …

Fixes missing context for actors called by MediatorCombinePipeline

---

packages/actor-query-operation-filter-sparqlee/lib/ActorQueryOperationFilterSparqlee.ts
packages/actor-query-operation-leftjoin-nestedloop/lib/ActorQueryOperationLeftJoinNestedLoop.ts
packages/actor-query-operation-orderby-sparqlee/lib/ActorQueryOperationOrderBySparqlee.ts

I still had this one stashed. Felt it couldn't hurt.

Document internally why some errors are silent in Filter, OrderBy and LeftJoin

---

.github/workflows/ci.yml
packages/actor-init-sparql/lib/ActorInitSparql-browser.ts
packages/actor-query-operation-service/lib/ActorQueryOperationService.ts
packages/actor-query-operation-sparql-endpoint/lib/ActorQueryOperationSparqlEndpoint.ts
packages/actor-query-operation-sparql-endpoint/package.json
packages/actor-query-operation-sparql-endpoint/test/ActorQueryOperationSparqlEndpoint-test.ts
packages/context-entries/lib/Keys.ts

This is in an initial attempt to solve https://github.com/comunica/comunica/issues/844.
As suggested in the issue description, in `actor-init-sparql` we save the original query string in the context, and in `actor-query-operation-sparql-endpoint`, we check this context entry and use it if it exists.
1. I've added `@comunica/context-entries` to the dependencies in `actor-query-operation-sparql-endpoint/package.json`, but running `yarn run lint` produces the following error:
> workspace/comunica/packages/actor-query-operation-sparql-endpoint/lib/ActorQueryOperationSparqlEndpoint.ts
9:1  error  '@comunica/context-entries' should be listed in the project's dependencies. Run 'npm i -S @comunica/context-entries' to add it  import/no-extraneous-dependencies
Is there something else I need to do? …

Send original SPARQL query string to endpoints

---

packages/mediator-combine-pipeline/README.md
packages/mediator-combine-pipeline/lib/MediatorCombinePipeline.ts
packages/mediator-combine-pipeline/test/MediatorCombinePipeline-test.ts

This PR adds an optional parameter to `MediatorCombinePipeline` which filters out actors with erroring tests.
This contains *no breaking changes*.
I'm not tied to this design - just proposing this now as it is useful to have something like this in the reasoning components I am working on

feat: Filter combine pipeline

---

packages/types/package.json

@rubensworks, as you suggested, this should fix `Namespace '"[...]/node_modules/@rdfjs/types/index"' has no exported member [...]` errors when running `tsc` on a package depending on `@comunica/types@^2.0.1`.

fix: require @rdfjs/types version

---

README.md

Closes #533
Also categorises the preconfigured engines within the readme

chore: Add reasoning engines to readme

---

packages/actor-query-operation-extend/package.json
packages/actor-query-operation-filter-sparqlee/package.json
packages/actor-query-operation-group/package.json
packages/actor-query-operation-leftjoin/package.json
packages/actor-query-operation-orderby-sparqlee/package.json
packages/actor-query-operation-orderby-sparqlee/test/ActorQueryOperationOrderBySparqlee-test.ts
yarn.lock

The sorting order according to the SPARQL spec should be undefined < blank node < named node < literal
Closes #892

Properly sort named nodes, blank nodes and unbounded values

---

packages/actor-dereference-http/test/ActorDereferenceHttp-test.ts
packages/actor-rdf-resolve-hypermedia-sparql/test/RdfSourceSparql-test.ts
packages/bus-http/lib/ActorHttp.ts
packages/bus-http/package.json
yarn.lock

The only useful line in this module was exporting globally the ReadableStream polyfill provided by 'web-streams-ponyfill'

Removes dependency on 'web-streams-node'

---

packages/actor-query-result-serialize-stats/lib/ActorQueryResultSerializeStats.ts
packages/actor-query-result-serialize-stats/test/ActorQueryResultSerializeStats-test.ts

Uses performance.now instead of process.hrtime

---

packages/actor-http-native/lib/ActorHttpNative.ts
packages/actor-http-native/lib/Requester.ts
packages/actor-query-result-serialize-json/lib/ActorQueryResultSerializeJson.ts
packages/actor-query-result-serialize-simple/lib/ActorQueryResultSerializeSimple.ts
packages/actor-query-result-serialize-sparql-xml/lib/ActorQueryResultSerializeSparqlXml.ts
packages/actor-rdf-resolve-quad-pattern-hypermedia/lib/MediatedLinkedRdfSourcesAsyncRdfIterator.ts

setTimeout(X) runs the callback on the next event cycle
except if there is more than 5 nested setTimeout.
In this case it waits at least 4ms.
This should be fine because we are not overusing setTimeout in Comunica.

Replace setImmediate by setTimeout

---

packages/actor-init-query/webpack.config.js

Resolves #1053 
My main question is - does the `ProvidePlugin` removed in https://github.com/comunica/comunica/pull/1023/files need to be introduced

fix: polyfill Buffer in webpack

---

packages/actor-http-fetch/lib/ActorHttpFetch.ts
packages/actor-http-fetch/lib/FetchInitPreprocessor-browser.ts

Related issue: https://github.com/comunica/comunica-feature-solid/issues/30
I used https://github.com/remodietlicher/comunica-solid-react-test to test the fix. 
To replicate the fix clone the repo, and use `yarn link` in the `packages/actor-http-fetch` directory on this branch to test the fixed version
Also added a small refactor that i saw, the tests were unaffected by it so i assume its good but let me know if its not then ill remove it :v:

Fix Headers not being sent

---

package.json
packages/actor-init-query/webpack.config.js
yarn.lock

This should fix the issue with the browser builds producing an error about `Buffer` not being defined. The `Buffer` global needs to be filled in separately from the `buffer` import (which has already been added). This was done for the jQuery-Widget.js but apparently Comunica does browser builds directly from here, as well. Apologies for that!
~~When it will be fixed here, [the corresponding fix](https://github.com/comunica/jQuery-Widget.js/commit/049b4f3828338bfb0b11a998218c7e229513755a) can likely be removed from the jQuery-Widget.js.~~ Actually it probably cannot... need to try.
The workaround here needs to be removed when the parsing library will be updated to no longer need it, I think: [sparqljson-parse.js#42](https://github.com/rubensworks/sparqljson-parse.js/issues/42)

Add Buffer global polyfill for Webpack

---

.gitignore

For the convenience of vs code users, since web storm config file are already ignored.

ignore also .vscode file

---

packages/actor-init-query/lib/ActorInitQueryBase.ts
packages/actor-init-query/lib/cli/CliArgsHandlerQuery.ts
packages/actor-init-query/test/ActorInitQuery-test.ts
packages/actor-query-operation-construct/lib/ActorQueryOperationConstruct.ts
packages/actor-query-operation-describe-subject/lib/ActorQueryOperationDescribeSubject.ts
packages/actor-query-operation-describe-subject/test/ActorQueryOperationDescribeSubject-test.ts

using the CLI interface the user can use the flag `--localizeBlankNodes` to force the application to use or not the blank node localization for the construct and describe query.
followup to #1063

feature/localizeBlankNodes expose to the cli interface.

---

README.md

I think it's convenient to have access to the documentation directly from the readme instead of having to go to the website then clicking on the doc link, and another doc link to access the code documentation.

Code documentation badge added to the readme

---

packages/actor-query-operation-ask/lib/ActorQueryOperationAsk.ts

Refactors the implementation to use `.take` which should allow the stream to close faster once https://github.com/RubenVerborgh/AsyncIterator/pull/45 is merged

refactor: QueryOperationAsk

---

packages/actor-init-query/test/HttpServiceSparqlEndpoint-test.ts

Reset cluster module after use in HttpServiceSparqlEndpoint-test.

fix: failing node 14 tests

---

.componentsjs-generator-config.json
engines/query-sparql-file/lib/QueryEngine.ts
engines/query-sparql-rdfjs/lib/QueryEngine.ts
engines/query-sparql/lib/QueryEngine.ts
package.json
packages/actor-init-query/lib/ActorInitQuery.ts
packages/actor-init-query/lib/ActorInitQueryBase.ts
packages/actor-init-query/lib/QueryEngineBase.ts
packages/actor-init-query/test/ActorInitQueryBase-test.ts
packages/actor-init-query/test/QueryEngineBase-test.ts
packages/types/lib/IQueryEngine.ts
yarn.lock

Hey @Ruben
addressing issue https://github.com/comunica/comunica/issues/949, I created this PR.
I had to add an ignoreComponent record to `.componentsjs-generator-config.json`'s as it does not seem to support Partial correctly which is used here for context type support in the IDE.
I hope this has caught the right direction and happy for feedback :)

Chore: improve context key injection

---

jest.config.js
packages/actor-init-query/test/HttpServiceSparqlEndpoint-test.ts
packages/bus-http/lib/ActorHttp.ts

- global.ReadableStream is only modify when it is undefined
- Unit test related to solid-client-authn are ignore as the package doesn't support it
- Unit test of error modified to take into account the new error string of node v19
- Before v19: `Invalid POST body with context received ('{"a:"b"}'): Expected ':' after property name in JSON at position 5`
- v19: `Invalid POST body with context received ('{"a:"b"}'): Unexpected token b in JSON at position 5`
close #1141

Fix errors related to "[assignement of] read only property" and unit test when using node v19

---

packages/actor-rdf-resolve-quad-pattern-string-source/README.md
packages/actor-rdf-resolve-quad-pattern-string-source/lib/ActorRdfResolveQuadPatternStringSource.ts
packages/actor-rdf-resolve-quad-pattern-string-source/package.json
packages/actor-rdf-resolve-quad-pattern-string-source/test/ActorRdfResolveQuadPatternStringSource-test.ts

The changes here were inspired by #1143, where the string source actor was parsing the source separately for each pattern, which in turn made the blank node identifiers (after parsing) different for each pattern. Queries with multiple pattern would therefore not produce any results.
The following changes were made to `ActorRdfResolveQuadPatternStringSource`:
* Added a cache with the data source (object) as key and the (promise of) parsed RDF data as value, so any subsequent requests to resolve a pattern based on a string source will use the same parse result for the same source object.
* Added `cacheSize` parameter to configure the cache size, with default 100. When set to 0, the actor will not cache the results and the bug will reappear, but it might be interesting for someone to try it …

Add source cache to string source actor

---

packages/actor-rdf-parse-shaclc/lib/ActorRdfParseShaclc.ts
packages/actor-rdf-parse-shaclc/package.json
packages/actor-rdf-parse-shaclc/test/ActorRdfParseShaclc-test.ts
yarn.lock

This is needed to allow it to be used in packages like rdf-parse (see https://github.com/rubensworks/rdf-parse.js/pull/48/files)

fix: allow shaclc parser to pipe

---

packages/actor-rdf-resolve-hypermedia-qpf/lib/RdfSourceQpf.ts
packages/actor-rdf-resolve-hypermedia-qpf/test/RdfSourceQpf-test.ts

We observed where if we execute the query:
```
PREFIX ldp: <http://www.w3.org/ns/ldp#>
SELECT * WHERE {
GRAPH ?g {
?s ldp:contains ?o .
}
}
```
by itself over a QPF endpoint then the correct results are returned; but if we use the same engine to _first_ execute the query:
````
SELECT * WHERE { ?s <http://www.w3.org/ns/ldp#contains> ?o }
````
then no results are returned.
This is because variables, and the default graph have both been given and id of the empty string and so an empty stream of results was being cached when searching over the default graph with `SELECT * WHERE { ?s <http://www.w3.org/ns/ldp#contains> ?o }` and then this cached stream was incorrectly being re-used when executing the query
```
PREFIX ldp: <http://www.w3.org/ns/ldp#>
SELECT * WHERE {
GRAPH ?g {
?s ldp:contains …
```

fix: don't cache QPF default graph as variable

---

.eslintrc.js
engines/query-sparql/test/QuerySparql-solid-test.ts
engines/query-sparql/test/QuerySparql-test.ts
packages/actor-dereference-http/test/ActorDereferenceHttp-test.ts
packages/actor-http-fetch/lib/ActorHttpFetch.ts
packages/actor-http-fetch/lib/FetchInitPreprocessor.ts
packages/actor-http-fetch/test/ActorHttpFetch-test.ts
packages/actor-http-native/lib/ActorHttpNative.ts
packages/actor-http-native/test/ActorHttpNative-test.ts
packages/actor-init-query/lib/ActorInitQuery-browser.ts
packages/actor-rdf-resolve-hypermedia-sparql/test/RdfSourceSparql-test.ts
packages/bus-http/lib/ActorHttp.ts
packages/jest/lib/index.ts

`global` doesn't exist in browser environments.
`globalThis` refers to `global` in node and `window` in browser.
cc @constraintAutomaton

fix: use `globalThis` rather than `global`

---

packages/actor-init-query/lib/cli/CliArgsHandlerQuery.ts

This should fix #1162. The issue seems to have been caused by the check for whether the args contain that entry, where it was using a simple if clause, so when it was actually set in the args but was false, the check would not pass and the false value would not be assigned to the context.

Fix: localizeBlankNodes command line argument not assigned to context when false

---

engines/query-sparql-file/bin/http.ts
engines/query-sparql-file/package.json
engines/query-sparql/bin/http.ts
engines/query-sparql/package.json
lerna.js
packages/actor-http-native/lib/ActorHttpNative.ts
packages/actor-http-native/package.json
packages/actor-init-query/lib/HttpServiceSparqlEndpoint.ts
packages/actor-init-query/lib/cli/CliArgsHandlerBase.ts
packages/actor-init-query/package.json
packages/actor-query-result-serialize-stats/lib/ActorQueryResultSerializeStats.ts
packages/actor-query-result-serialize-stats/package.json
packages/logger-bunyan/lib/stream/BunyanStreamProviderStderr.ts
packages/logger-bunyan/lib/stream/BunyanStreamProviderStdout.ts
packages/logger-bunyan/package.json
packages/logger-pretty/lib/LoggerPretty.ts
packages/logger-pretty/package.json
packages/packager/bin/package.ts
packages/packager/package.json
packages/runner-cli/bin/run.ts
packages/runner-cli/lib/ArgsRunner.ts
packages/runner-cli/package.json
packages/runner/bin/compile-config.ts
packages/runner/lib/Setup.ts
packages/runner/package.json

Uses the process shim rather than a global. It may be possible to remove the polyfills of process after this PR but we need to evaluate if any dependents use process globally (unless there are already tests in place to detect that in Comunica?)

fix: use process shim

---

packages/bindings-factory/lib/Bindings.ts

These work correctly with any `RDF.Bindings`, not only Comunica's implementation of `Bindings`.
Not only is this currently stopping these methods from working with other implementations of `Bindings`, they're stopping Comunica's `Bindings` from being interchangeable with other `Bindings` in general, at the type level. Consider the following code:
```ts
import type * as RDF from '@rdfjs/types';
import { Bindings } from "@comunica/bindings-factory";
function doSomethingWithBindings(bindings: RDF.Bindings) {}
declare const comunicaBindings: Bindings;
doSomethingWithBindings(comunicaBindings)
```
This causes a TypeScript error, because `comunicaBindings` cannot be passed to `doSomethingWithBindings()`, because the types are incompatible, because `comunicaBindings.merge()` takes a Comunica …

`Bindings` `merge()` and `mergeWith()` accept RDF.Bindings

---

engines/query-sparql/package.json
package.json
packages/actor-query-operation-extend/package.json
packages/actor-query-operation-filter-sparqlee/package.json
packages/actor-query-operation-group/package.json
packages/actor-query-operation-leftjoin/package.json
packages/actor-query-operation-orderby-sparqlee/package.json
yarn.lock

Bump sparqlee version and add spec tests for sparql 1.2 date support. Depends on: https://github.com/rubensworks/rdf-test-suite.js/pull/91

feat: bump sparqlee version

---

packages/actor-rdf-parse-shaclc/lib/ActorRdfParseShaclc.ts
packages/actor-rdf-parse-shaclc/package.json
packages/actor-rdf-parse-shaclc/test/ActorRdfParseShaclc-test.ts
yarn.lock

Without this patch `urn:x-base:default` is used as the base for relative IRIs in shaclc documents.
I would appreciate it if a release containing this patch could be made fairly quickly.

fix: provide baseIRI for shaclc

---

.componentsjs-generator-config.json

This PR aims to fix a warning thrown when running `yarn install`:
> Skipped generating invalid package at ".../packages/expression-evaluator": Invalid package: Missing 'lsd:components' in ...packages/expression-evaluator/package.json

fix: components.js warning on expression evaluator

---

packages/actor-query-operation-sparql-endpoint/lib/ActorQueryOperationSparqlEndpoint.ts
packages/actor-query-operation-sparql-endpoint/package.json
packages/actor-query-operation-sparql-endpoint/test/ActorQueryOperationSparqlEndpoint-test.ts

Fixes #1257 by enabling `sparqlStar` on `sparqlalgebrajs.toSparql` and using an updated version of `fetch-sparql-endpoint`

Enable SPARQL-star support for Update queries on `@comunica/actor-query-operation-sparql-endpoint`

---

packages/actor-abstract-mediatyped/lib/ActorAbstractMediaTypedFixed.ts
packages/actor-abstract-mediatyped/test/ActorAbstractMediaTypedFixed-test.ts
packages/actor-rdf-parse-jsonld/lib/ActorRdfParseJsonLd.ts
packages/actor-rdf-parse-jsonld/test/ActorRdfParseJsonLd-test.ts

This fixes a small error about trying to call the endsWith on mediaType string when the string is undefined. The other parse actors also report undefined as unsupported media type, so this change also aligns the actor with those.

Skip calling endsWith on mediaType when mediaType is undefined

---

.eslintrc.js
engines/query-sparql/test/QuerySparql-test.ts
packages/actor-dereference-http/test/MediaTypesToAcceptString-test.ts
packages/actor-query-result-serialize-table/lib/ActorQueryResultSerializeTable.ts
packages/logger-bunyan/test/LoggerBunyan-test.ts

Here is a small set of changes to make the ESLint rule overrides more specific, because the overrides are used to disable rules and it might make sense to disable then with the smallest possible scope. I have also added comments for what triggers the rules to make it easier to understand why the overrides exist.
There are also a couple of code changes that help make some rule overrides unnecessary:
* Replacing the use of array joins for string repetition with the repeat function from string allows re-enabling the `unicorn/no-new-array` rule.
* Making sure the imports in two files are at the top of the files allows re-enabling the `import/first` rule. This was done by moving some imports to the top of one file, and by removing an unmock workaround that did not appear to have any impact on …

Make ESLint rule overrides more specific and re-enable a number of rules

---

.github/workflows/ci.yml

Here is a small set of changes that I was thinking might make sense, but that will need some discussion I feel. There are three changes:
1. Update `actions/cache` to v3, because v2 used Node 12 and that has been deprecated. The new one seems to work the same way as the previous one.
2. Use `--frozen-lockfile` instead of `--pure-lockfile`, because the pure option only skips generating a lockfile, whereas the frozen one ensures that the lockfile and package.json are synced by failing if any lockfile changes would result from the installation according to [the documentation](https://classic.yarnpkg.com/lang/en/docs/cli/install/).
3. Always run linter first, then tests, and then everything else. I feel like this would make sense, because linting should be the cheapest and fastest to do, and …

Update actions/cache to v3, use --frozen-lockfile instead of --pure-lockfile, cancel old workflow when new one is queued

---

packages/expression-evaluator/test/integration/util/Ordering-test.ts
packages/expression-evaluator/test/spec/sparql-12/sep-0002/adjust_time-01-spec-test.ts

I looked at the expression evaluator tests that are skipped. Seems like only one skipped test can be enabled because the other skipped tests need SparqlAlgebra to support `ADJUST`.

test: enable langString type comparison

---

packages/runner-cli/lib/ArgsRunner.ts

This should fix #1276 and allow the use of both relative and absolute paths for `COMUNICA_CONFIG`. The prepending of current working directory seems to have been unnecessary, as the code also works without it.
Any feedback is welcome. :slightly_smiling_face:

Support relative and absolute paths for `COMUNICA_CONFIG`

---

packages/actor-hash-bindings-sha1/test/ActorHashBindingsSha1-test.ts
packages/bindings-factory/test/bindingsToString-test.ts

The `bindingsToString` function produces a record where the keys are not in sorted order, but rather in the order in which they were assigned to the bindings object. Therefore, a bindings object that has identical keys and values but in different order will serialize into a different string.
This change adds a unit test to make sure that happens consistently and also makes sure it is made explicit by having a test for it - otherwise someone might assume that the function produces the same string for a bindings object with the same keys and values.
Any feedback is welcome. :slightly_smiling_face:

Enforce `bindingsToString` key ordering with a unit test

---

packages/bindings-factory/lib/BindingsFactory.ts

My project was reporting a type failure in `BindingsFactory.d.ts`, so I dug in to investigate. It was because `fromBindings()` needs to accept any `RDF.Bindings`, not just Comunica `Bindings`.
It looks like the reason that wasn't failing in Comunica itself is that `strictFunctionTypes` was off. #1233 tried to turn that back on and address various issues it was covering up. But as noted there, it wasn't quite that simple to turn on. For now, this addresses the original type issue I hit.

Fix `BindingsFactory`'s `fromBindings` type

---

packages/actor-http-fetch/test/ActorHttpFetch-test.ts
packages/bus-http/lib/ActorHttp.ts
packages/bus-http/package.json
yarn.lock

Hopefully closes https://github.com/comunica/comunica-feature-link-traversal/issues/121
This fork uses the latest version of the readable-stream dependency.

Switch to `@smessie/readable-web-to-node-stream@^3.0.3`

---

packages/bus-rdf-update-quads/lib/ActorRdfUpdateQuadsDestination.ts
packages/bus-rdf-update-quads/test/ActorRdfUpdateQuadsDestination-test.ts

Resolves #1301.
This is a follow up work to #1326. It includes a hotfix to prevent race condition when inserting and deleting quads to/from destination. Delete and update operations are now being run in sequence.

Hotfix DELETE/INSERT update operation order

---

packages/actor-http-fetch/test/ActorHttpFetch-test.ts
packages/actor-http-wayback/test/ActorHttpWayback-test.ts
packages/bus-http/lib/ActorHttp.ts
packages/bus-http/package.json
yarn.lock

Here is a small set of changes to migrate from `@smessie/readable-web-to-node-stream` to `readable-from-web`.
I had to adjust the tests a little, as well, including one `ActorHttpWayback` test that was missing the `closed` promise and the `cancel` function from its mock implementation of WHATWG ReadableStream.
The `@smessie/readable-web-to-node-stream` package is still in yarn.lock because it is required by 2.x versions of Comunica, which are required by `rdf-parse`, which are required by `componentsjs`.
Is there something that is not obvious, but that should also be checked or adjusted with this change? :thinking:

Migrate from readable-web-to-node-stream to readable-from-web

---

packages/actor-query-source-identify-hypermedia-sparql/package.json
packages/actor-rdf-update-hypermedia-sparql/package.json
yarn.lock

This is just a small change to bump the `fetch-sparql-endpoint` library to version 5 now that it has been released.
Any feedback is welcome.

Update fetch-sparql-endpoint to v5

---

packages/actor-context-preprocess-query-source-identify/lib/ActorContextPreprocessQuerySourceIdentify.ts
packages/actor-context-preprocess-query-source-identify/test/ActorContextPreprocessQuerySourceIdentify-test.ts

This should fix #1336 where query sources did not have any context entries.
Based on the comment in that issue by @rubensworks (correct me if I am wrong), context preprocessing is always expected to happen, but the code in the responsible actor was only preprocessing existing contexts. Thus, for a source without any context to begin with, no preprocessing would be done. This led to the exclusion of the traverse flag from link traversal sources.
The changes here remove the requirement to have a context added beforehand, by preprocessing either an existing context or an empty new one, and adding that to the source.
I have tested this locally by rebuilding the `solid-default` web client and running the query as it was done in the issue. The original query only produced 100 entries from …

Always add preprocessed context to unidentified query sources

---

packages/actor-query-result-serialize-json/lib/ActorQueryResultSerializeJson.ts
packages/actor-query-result-serialize-json/package.json
packages/actor-query-result-serialize-json/test/ActorQueryResultSerializeJson-test.ts
packages/actor-query-result-serialize-simple/lib/ActorQueryResultSerializeSimple.ts
packages/actor-query-result-serialize-simple/package.json
packages/actor-query-result-serialize-sparql-csv/lib/ActorQueryResultSerializeSparqlCsv.ts
packages/actor-query-result-serialize-sparql-json/lib/ActorQueryResultSerializeSparqlJson.ts
packages/actor-query-result-serialize-sparql-json/package.json
packages/actor-query-result-serialize-sparql-tsv/lib/ActorQueryResultSerializeSparqlTsv.ts
packages/actor-query-result-serialize-sparql-xml/lib/ActorQueryResultSerializeSparqlXml.ts
packages/actor-query-result-serialize-sparql-xml/lib/XmlSerializer.ts
packages/actor-query-result-serialize-sparql-xml/package.json
packages/actor-query-result-serialize-sparql-xml/test/XmlSerializer-test.ts
packages/actor-query-result-serialize-stats/lib/ActorQueryResultSerializeStats.ts
packages/actor-query-result-serialize-stats/package.json
packages/actor-query-result-serialize-table/lib/ActorQueryResultSerializeTable.ts
yarn.lock

This PR resolves backpressure issues in the serialisers (partly resolving #759).
It also makes it easy to migrate to having serialisers return `AsyncIterator`s rather than `Readable`s as we are now largely just wrapping `Readable`s around `AsyncIterator`s. If there is demand for consuming the serialised information as `AsyncIterator`s then one option would be to extend the output interface to be
```ts
export interface IActorQueryResultSerializeOutput extends IActorOutput {
/**
* A readable string stream in a certain SPARQL serialization that was serialized.
*/
data: NodeJS.ReadableStream;
iterator: AsyncIterator<string>;
}
```
and implement it such that the `data` key is a getter which only creates a readable stream wrapping the asynciterator when the `data` key is retrieved.
cc …

backpressure: fix serialisation backpressure issues

---

.github/workflows/ci.yml

Bump CI Workflow Versions
https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/
[CI Annotations](https://github.com/comunica/comunica/actions/runs/9243577720?pr=1360)

feat: bump CI workflow versions

---

engines/query-sparql/test/QuerySparql-test.ts
packages/actor-query-operation-group/lib/GroupsState.ts
packages/actor-query-operation-group/test/ActorQueryOperationGroup-test.ts

Fixed a bug where the order of count operations influenced the result. See https://github.com/comunica/comunica/issues/1312
The problem was that we avoided counting a binding twice, even though it was for different aggregate expressions.
I solved it by hashing the binding with the expression variable and checking that this combination doesn't occur twice.
I'm not sure about the best practices when it comes to hashing, so it would be great if someone could update me on that.

Fixed a bug where the order of count operations influenced the result

---

lerna-custom-script.js
packages/actor-http-memento/lib/ActorHttpMemento.ts
packages/actor-http-memento/package.json
packages/actor-http-native/lib/Requester-browser.ts
packages/actor-http-native/package.json
yarn.lock

migrate `parse-link-header` to `http-link-header` in preparation for ESM support

chore: migrate parse-link-header to http-link-header

---

packages/actor-query-source-identify-hypermedia-annotate-source/README.md

The `ActorQuerySourceIdentifyHypermediaAnnotateSource` actor produces incomplete why-provenance annotations when the `aggregateStore` is enabled. To reflect this limitation I've updated the README.md

Update README.md of actor-query-source-identify-hypermedia-annotate-source

---

packages/actor-optimize-query-operation-prune-empty-source-operations/lib/ActorOptimizeQueryOperationPruneEmptySourceOperations.ts
packages/actor-optimize-query-operation-prune-empty-source-operations/test/ActorOptimizeQueryOperationPruneEmptySourceOperations-test.ts

This is a fix for an issue where the `traverse` key was being extracted from the source context by `ActorOptimizeQueryOperationPruneEmptySourceOperations` but not from the action context. When the source context does not have the traversal key, and the pruning logic is run, this would result in the pruning of all operations assigned to that source, even when the action context itself would have the traversal flag in it.
This should fix #1498

Fix traversal flag extraction for operation pruning 

---

packages/actor-http-retry/lib/ActorHttpRetry.ts
packages/actor-http-retry/test/ActorHttpRetry-test.ts

This is a workaround for DBPedia SPARQL endpoint sending a 405 instead of 429 for rate limiting, which should be considered 429 by the client for retry purposes. Assuming the same software could be used in other SPARQL endpoints, as well, there is no URI-specific handling, but instead just a check for 405 with `Retry-After`, which should be sufficient.
This also fixes a small bug with the timeout calculation for clearing up old delays.

Add workaround for DBPedia SPARQL HTTP status 405 with Retry-After

---

engines/config-query-sparql/config/config-default-v4-1-0.json
engines/config-query-sparql/config/http/actors-limit-rate.json
engines/config-query-sparql/config/http/actors-v4-1-0.json
engines/query-sparql/package.json
packages/actor-http-limit-rate/README.md
packages/actor-http-limit-rate/lib/ActorHttpLimitRate.ts
packages/actor-http-limit-rate/lib/index.ts
packages/actor-http-limit-rate/package.json
packages/actor-http-limit-rate/test/ActorHttpLimitRate-test.ts

Here is a draft PR for the simple rate limit actor, after a lot of revisions back and forth.
* The actor current keeps track of the *n* previous request durations as a sliding list/window (not sure what the correct term it), measured from when the request was sent, to when the server replied, excluding the time taken to read the request body. Based on these previous request durations, it spaces out future requests in a way that avoids request spikes.
* The actor also maintains a concurrent request limit per host. When a request to a host is successful, and there is a considerable number of requests in queue for it (currently >10x the concurrent request limit), the actor will increase the concurrent request limit by 1. When a request fails, it will halve the limit.
The actor is really …

Add HTTP rate limit actor

---

packages/actor-rdf-join-inner-multi-bind-source/lib/ActorRdfJoinMultiBindSource.ts
packages/actor-rdf-join-inner-multi-bind-source/test/ActorRdfJoinMultiBindSource-test.ts
packages/actor-rdf-join-inner-multi-bind/lib/ActorRdfJoinMultiBind.ts
packages/actor-rdf-join-inner-multi-bind/test/ActorRdfJoinMultiBind-test.ts

This should fix the issue with extremely verbose debug logging after VoID descriptions are discovered.

Avoid printing all metadata in join logging

---

packages/types/lib/IQueryContext.ts

This PR adds the `distinctConstruct` key to the `IQueryContextCommon` interface.
Related to #1510.

Add distinctConstruct key to IQueryContextCommon

---

.github/workflows/ci.yml

This fixes the false duplicates in Coveralls reports, where the same lines would be reported multiple times. It turns out this issue was caused by the OS not being taken into account for the generation of the identifier.

Fix Coveralls result key to avoid false duplicates

---

packages/actor-dereference-http/test/ActorDereferenceHttp-test.ts
packages/actor-dereference-rdf-parse/test/ActorDereferenceRdfParse-test.ts
packages/bus-dereference/lib/ActorDereferenceBase.ts
packages/bus-dereference/lib/ActorDereferenceParse.ts

This is a small PR to address three issues I discovered while testing out the master branch with link traversal:
1. The URL of a failed fetch request does not get reported, but the actor does. This makes the warning messages useless, so I added the URL as extra data to the error message.
2. The media type cascade logic seemed off, so I changed it to prefer the variables, and only fall back to a function call as last resort. This seems to have changed nothing in my tests, but should avoid a function call if one of the variables does have a non-empty value.
3. The entire RDF parse operation was being attempted on sources that failed to be dereferenced, so I added that part of the code behind an if statement to avoid the redundant parse error messages when dereferencing fails. The error …

Fixes to dereference error handling

---

package.json

After some local experimentation, it seems that limiting the worker count can make the tests go faster, and consume a lot less memory. This is probably also the reason why the worker count has been limited in the CI originally.
However, a fixed limit of 4 translates to no limit at all for the MacOS runner, that has [3 cores](https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories) and considerably less memory than the other ones. I think this is the reason why the tests fail so often on MacOS.
This PR changes the static limit of 4 workers to a relative limit of 50%.

Remove Jest maxWorkers as redundant

---

packages/actor-rdf-join-inner-multi-bind/lib/ActorRdfJoinMultiBind.ts
packages/utils-query-operation/lib/MaterializeBindings.ts
packages/utils-query-operation/test/MaterializeBindings-test.ts

After a lot of debugging, it turned out the source assignment error in #1519 is most likely caused by the flattening of joins, when using the `createJoin` function from `sparqlalgebrajs`, as it seems to strip out the metadata from join entries when it performs the flattening step.
Disabling flattening seems to fix it, so I changed the parts of the code where I ran into this issue to not do flattening when any of the join entries have metadata associated with them.
After this change, the query in #1519, as well as another consistently reproducible query (`020_ns` from @ecrum19's example collection) no longer crash due to source assignment issues. Neither of them seem to complete within a reasonable amount of time, either, but at least the error is gone.
Any feedback would be welcome, …

Avoid flattening joins with input-specific metadata

---

packages/actor-query-source-identify-hypermedia-sparql/lib/ActorQuerySourceIdentifyHypermediaSparql.ts
packages/actor-query-source-identify-hypermedia-sparql/test/ActorQuerySourceIdentifyHypermediaSparql-test.ts

Added the `forceSourceType?: boolean` arg to the `ActorQuerySourceIdentifyHypermediaSparql` actor. 
This arg allows the passing of a `Boolean` value to force all sources to be interpreted as SPARQL Endpoints. 
Along with the addition of this argument, also added unit tests to extend 100% test coverage.

Changes to ActorQuerySourceIdentifyHypermediaSparql

---

packages/actor-query-source-identify-hypermedia-sparql/README.md
packages/actor-query-source-identify-hypermedia-sparql/lib/ActorQuerySourceIdentifyHypermediaSparql.ts
packages/actor-query-source-identify-hypermedia-sparql/lib/QuerySourceSparql.ts
packages/actor-query-source-identify-hypermedia-sparql/package.json
packages/actor-query-source-identify-hypermedia-sparql/test/ActorQuerySourceIdentifyHypermediaSparql-test.ts
packages/actor-query-source-identify-hypermedia-sparql/test/QuerySourceSparql-test.ts
packages/actor-rdf-metadata-extract-void/lib/ActorRdfMetadataExtractVoid.ts
packages/actor-rdf-metadata-extract-void/lib/Estimators.ts
packages/actor-rdf-metadata-extract-void/test/ActorRdfMetadataExtractVoid-test.ts
packages/actor-rdf-metadata-extract-void/test/Estimators-test.ts
packages/types/lib/IDataset.ts
packages/utils-query-operation/lib/CardinalityEstimators.ts
packages/utils-query-operation/lib/index.ts
packages/utils-query-operation/package.json
packages/utils-query-operation/test/CardinalityEstimators-test.ts

This is the set of changes that are needed to use cached `COUNT` query results for SPARQL source cardinality estimation, even without VoID metadata available. The main change here is splitting the cardinality estimation from VoID metadata into two parts:
* Triple pattern cardinality estimates, provided by VoID, based on the formulae from Hagedorn et al. with some vocabulary-based heuristics applied on top.
* Operation cardinality estimates, moved to `utils-query-operation` that break down larger operations down to triple pattern level, and then use pattern cardinalities to construct the higher-level cardinality estimate. This involves some purpose-built heuristics at the moment, but ideally this logic would later be moved into a separate cardinality estimation bus or something for more …

Rework SPARQL source cardinality estimation to cache pattern counts

---

engines/config-query-sparql/config/query-source-identify-hypermedia/actors-sparql.json
engines/config-query-sparql/config/query-source-identify-hypermedia/actors.json
packages/actor-query-source-identify-hypermedia-sparql/README.md

Added the `forceSourceType` config parameter to the ReadMe.
Changed the path of `"@id": "urn:comunica:default:query-source-identify-hypermedia/actors#sparql"` to `"@id": "urn:comunica:default:query-source-identify-hypermedia/actors#sparql"` in configs within `query-source-identify-hypermedia` in the engine `query-sparql-config` to reflect current config structure.

small changes to actor-query-source-hypermedia-identify-sparql configs

---

packages/actor-optimize-query-operation-prune-empty-source-operations/lib/ActorOptimizeQueryOperationPruneEmptySourceOperations.ts

This is a fix for what appears to be a typo, where the variable names have an additional `?` in front of them, when there should be none. This issue was discovered by @ecrum19 during their experiments.

Fix variable names in empty operations pruning actor

---

engines/query-sparql-file/webpack.config.ts
engines/query-sparql-rdfjs-lite/webpack.config.ts
engines/query-sparql-rdfjs/webpack.config.ts
engines/query-sparql/webpack.config.ts
eslint.config.js
packages/actor-init-query/webpack.config.ts
tsconfig.eslint.json
yarn.lock

This is a quick fix for the issue that was pointed out, where moving the Webpack config to the monorepo root in 99997787ae6e034354ff83cec9e9e7b654e7c609 broke use-cases where it was inherited from the actor-init-query package.

Move primary Webpack config back to actor-init-query

---

.github/workflows/ci.yml

This contains the following changes:
* Adding Node 24 to CI
* Running everything on Node 18 by default, unless in a test matrix
* Fixing reference to a non-existing `matrix.node-version`

Fixes to CI Node versions

---

README.md

This is a small set of changes to fix some tiny annoyances with the CI badges that I have:
* Fix the indentation, because the badges are not indented, but everything else around them is.
* Remove the plastic style definitions from Gitter badges, because they look nothing like the other badges now.
* Lock the CI badge to master branch, I have no idea how or why, but this seems to fix the status showing up as failed, even though the latest run has been a success.
Any feedback would be welcome, though. I know this is a really random thing, but especially the CI badge has been bothering me for ages. :grimacing:

Fixes to readme badges

---

packages/actor-optimize-query-operation-prune-empty-source-operations/lib/ActorOptimizeQueryOperationPruneEmptySourceOperations.ts
packages/actor-optimize-query-operation-prune-empty-source-operations/test/ActorOptimizeQueryOperationPruneEmptySourceOperations-test.ts

This is a logic change to ensure Comunica follows the SPLENDID source assignment approach more carefully, by using ASK queries to avoid false positives caused by local cardinality estimation, that is used for pruning empty sources.
Previously, Comunica performed source assignment in a single pass, regardless of whether the estimate was produced locally using VoID descriptions or acquired from a remote source via COUNT query. This allows false positive source assignments for triple patterns with subject or object values that would restrict them to specific sources, because the VoID description does not encode subject or object information.
After this change, when the cardinality estimate from metadata is an estimate, and the source supports ASK queries, Comunica will issue an ASK query to …

Use ASK to verify cardinality estimate-based source assignments

---

packages/actor-optimize-query-operation-prune-empty-source-operations/lib/ActorOptimizeQueryOperationPruneEmptySourceOperations.ts
packages/actor-optimize-query-operation-prune-empty-source-operations/test/ActorOptimizeQueryOperationPruneEmptySourceOperations-test.ts

This is a change to ensure the merged action and source context is used during empty operation pruning, to avoid CORS issues when combining sources with and without authorization.

Ensure source context is used in hypermedia query sources

---

packages/utils-bindings-factory/README.md

As per discussion https://github.com/comunica/comunica/issues/1628#issuecomment-3326650747
The [bindings factory documentation](https://github.com/comunica/comunica/tree/master/packages/utils-bindings-factory) currently demonstrates usage via [@comunica/utils-data-factory](https://github.com/comunica/comunica/tree/master/packages/utils-data-factory), however that package appears to be a work in progress/placeholder, so anyone running the example given in the documentation will find it doesn't work.
The [tests for bindings factory](https://github.com/comunica/comunica/blob/master/packages/utils-bindings-factory/test/BindingsFactory-test.ts) use the [rdf-data-factory](https://github.com/rubensworks/rdf-data-factory.js) package instead - this PR just updates the documentation to reflect …

Update documentation for bindings factory

---

performance/benchmark-web/combinations/combination_0/input/queries/wikidata/author-birthday.rq
performance/benchmark-web/combinations/combination_0/input/queries/wikidata/paper-subjects.rq
performance/benchmark-web/combinations/combination_0/input/queries/wikidata/simple-count.rq
performance/benchmark-web/combinations/combination_0/input/queries/wikidata/sitelinks-lookup.rq
performance/benchmark-web/combinations/combination_1/input/queries/wikidata/author-birthday.rq
performance/benchmark-web/combinations/combination_1/input/queries/wikidata/paper-subjects.rq
performance/benchmark-web/combinations/combination_1/input/queries/wikidata/simple-count.rq
performance/benchmark-web/combinations/combination_1/input/queries/wikidata/sitelinks-lookup.rq
performance/benchmark-web/input/queries/wikidata/author-birthday.rq
performance/benchmark-web/input/queries/wikidata/paper-subjects.rq
performance/benchmark-web/input/queries/wikidata/simple-count.rq
performance/benchmark-web/input/queries/wikidata/sitelinks-lookup.rq

This is the version of the VALUES clause expansion actor that I used for the Wikidata experiments. It works around some source assignment issues by filling in the bindings into the operations directly, allowing for VALUES bindings without any matches at the source to be pruned during query optimisation, as well.
I will need to check the variable scoping, to make sure nothing gets substituted that is meant to be projected out of the query, now that I think of it... :sweat_smile: 
The idea is open for comments, though.

Add federated Wikidata queries to web benchmark
