packages/actor-rdf-resolve-quad-pattern-sparql-json/lib/ActorRdfResolveQuadPatternSparqlJson.ts
packages/actor-rdf-resolve-quad-pattern-sparql-json/test/ActorRdfResolveQuadPatternSparqlJson-test.ts

Convert blank nodes when solving SPARQL patterns

---

packages/actor-rdf-resolve-quad-pattern-qpf/lib/MediatedQuadSource.ts
packages/actor-rdf-resolve-quad-pattern-qpf/package.json
packages/actor-rdf-resolve-quad-pattern-qpf/test/ActorRdfResolveQuadPatternQpf-test.ts
packages/actor-rdf-resolve-quad-pattern-qpf/test/MediatedQuadSource-test.ts

This required some non-insignificant changes, so it might be good to have a review on this.
Fixes #152.

Fix no client-side filtering of non-matching quads, Closes #152

---

packages/actor-rdf-resolve-quad-pattern-federated/lib/ActorRdfResolveQuadPatternFederated.ts
packages/actor-rdf-resolve-quad-pattern-federated/lib/FederatedQuadSource.ts
packages/actor-rdf-resolve-quad-pattern-federated/test/FederatedQuadSource-test.ts

A straightforward fix, but might be good to double-check if I didn't do anything stupid.
Closes #265.

Fix federated actor stringifying sources

---

packages/actor-context-preprocess-rdf-source-identifier/lib/ActorContextPreprocessRdfSourceIdentifier.ts
packages/actor-init-sparql/config/sets/sparql-init.json

Makes sure sources are identified before querying

---

package.json
packages/actor-abstract-path/package.json
packages/actor-init-sparql/webpack.config.js
packages/actor-query-operation-bgp-empty/package.json
packages/actor-query-operation-construct/package.json
packages/actor-query-operation-path-one-or-more/package.json
packages/actor-query-operation-path-zero-or-one/package.json
packages/actor-query-operation-service/package.json
packages/actor-query-operation-sparql-endpoint/package.json
packages/actor-query-operation-values/package.json
packages/actor-rdf-dereference-paged-next/package.json
packages/actor-rdf-resolve-quad-pattern-federated/package.json
packages/actor-rdf-resolve-quad-pattern-file/package.json
packages/actor-rdf-resolve-quad-pattern-sparql-json/package.json
packages/bus-query-operation/package.json
packages/bus-rdf-resolve-quad-pattern/package.json
yarn.lock

Obsoletes a webpack config rule.

Upgrade asynciterator to v2.0.1

---

packages/actor-init-rdf-parse/test/ActorInitRdfParse-test.ts
packages/actor-rdf-parse-jsonld/test/ActorRdfParseJsonLd-test.ts

Noticed during my last pull request that code coverage was no longer at 100%

Add tests for uncovered code

---

packages/actor-context-preprocess-rdf-source-identifier/lib/ActorContextPreprocessRdfSourceIdentifier.ts
packages/actor-context-preprocess-rdf-source-identifier/test/ActorContextPreprocessRdfSourceIdentifier-test.ts

Randomly stumbled upon this while adding a new ldflex feature

Support source identification for single sources

---

package.json
packages/actor-abstract-path/package.json
packages/actor-optimize-query-operation-join-bgp/package.json
packages/actor-query-operation-from-quad/package.json
packages/actor-query-operation-path-alt/package.json
packages/actor-query-operation-path-inv/package.json
packages/actor-query-operation-path-link/package.json
packages/actor-query-operation-path-nps/package.json
packages/actor-query-operation-path-one-or-more/package.json
packages/actor-query-operation-path-seq/package.json
packages/actor-query-operation-path-zero-or-more/package.json
packages/actor-query-operation-sparql-endpoint/package.json
packages/actor-rdf-resolve-quad-pattern-sparql-json/package.json
packages/actor-sparql-parse-algebra/package.json
packages/bus-optimize-query-operation/package.json
yarn.lock

Update sparqlalgebrajs to 1.5.0

---

packages/actor-query-operation-orderby-sparqlee/lib/ActorQueryOperationOrderBySparqlee.ts

Fix bug in orderby due to multiple transforms on same stream

---

packages/actor-init-sparql/lib/HttpServiceSparqlEndpoint.ts

Just discovered this problem while working on the tutorial and trying to query my own sparql endpoint through the widget.

Add CORS headers for SPARQL interface

---

__mocks__/fs.js
__mocks__/http.js
__mocks__/url.js
package.json
packages/actor-init-sparql-file/bin/http.ts
packages/actor-init-sparql/__mocks__/index.js
packages/actor-init-sparql/bin/http.ts
packages/actor-init-sparql/lib/HttpServiceSparqlEndpoint.ts
packages/actor-init-sparql/test/HttpServiceSparqlEndpoint-test.ts
yarn.lock

Add unit tests for HttpServiceSparqlEndpoint. Also refactor the code itself a little.

Http service sparql endpoint tests

---

packages/actor-abstract-bindings-hash/components/Actor/AbstractBindingsHash.jsonld
packages/actor-abstract-bindings-hash/components/Actor/AbstractFilterHash.jsonld
packages/actor-abstract-bindings-hash/components/context.jsonld
packages/actor-abstract-bindings-hash/lib/AbstractBindingsHash.ts
packages/actor-abstract-bindings-hash/test/AbstractBindingsHash-test.ts
packages/actor-query-operation-distinct-hash/lib/ActorQueryOperationDistinctHash.ts
packages/actor-query-operation-reduced-hash/lib/ActorQueryOperationReducedHash.ts
packages/core/components/ActionObserver.jsonld
packages/core/components/Actor.jsonld
packages/core/components/Logger.jsonld
packages/core/components/Mediator.jsonld
packages/core/components/context.jsonld
packages/logger-bunyan/components/Logger/Bunyan/Stream.jsonld

Close #487 
This should not be merged yet as it is a work in progress.

Fix various small component naming issues

---

packages/actor-init-http/test/ActorInitHttp-test.ts
packages/actor-rdf-dereference-http-parse/test/ActorRdfDereferenceHttpParse-test.ts
packages/actor-rdf-resolve-hypermedia-sparql/test/RdfSourceSparql-test.ts
packages/actor-rdf-resolve-quad-pattern-sparql-json/test/ActorRdfResolveQuadPatternSparqlJson-test.ts
packages/bus-http/lib/ActorHttp.ts
packages/bus-http/package.json
yarn.lock

Fixes #275 with a single package.json edit in `bus-http`
```
Test Suites: 147 passed, 147 total
Tests:       2071 passed, 2071 total
Snapshots:   0 total
Time:        18.17s, estimated 45s
Ran all test suites.
```

Swap node-web-streams package to web-streams-node.

---

package.json
packages/actor-abstract-path/package.json
packages/actor-optimize-query-operation-join-bgp/package.json
packages/actor-query-operation-from-quad/package.json
packages/actor-query-operation-path-alt/package.json
packages/actor-query-operation-path-inv/package.json
packages/actor-query-operation-path-link/package.json
packages/actor-query-operation-path-nps/package.json
packages/actor-query-operation-path-one-or-more/package.json
packages/actor-query-operation-path-seq/package.json
packages/actor-query-operation-path-zero-or-more/package.json
packages/actor-query-operation-sparql-endpoint/package.json
packages/actor-rdf-resolve-hypermedia-sparql/package.json
packages/actor-rdf-resolve-quad-pattern-sparql-json/package.json
packages/actor-sparql-parse-algebra/package.json
packages/bus-optimize-query-operation/package.json
yarn.lock

Update to SparqlAlgebra.js 2.2.0

---

package.json
packages/actor-abstract-path/package.json
packages/actor-optimize-query-operation-join-bgp/package.json
packages/actor-query-operation-from-quad/package.json
packages/actor-query-operation-path-alt/package.json
packages/actor-query-operation-path-inv/package.json
packages/actor-query-operation-path-link/package.json
packages/actor-query-operation-path-nps/package.json
packages/actor-query-operation-path-one-or-more/package.json
packages/actor-query-operation-path-seq/package.json
packages/actor-query-operation-path-zero-or-more/package.json
packages/actor-query-operation-slice/lib/ActorQueryOperationSlice.ts
packages/actor-query-operation-slice/test/ActorQueryOperationSlice-test.ts
packages/actor-query-operation-sparql-endpoint/package.json
packages/actor-rdf-resolve-hypermedia-sparql/package.json
packages/actor-rdf-resolve-quad-pattern-sparql-json/package.json
packages/actor-sparql-parse-algebra/package.json
packages/bus-optimize-query-operation/package.json
yarn.lock

Support slicing of quad streams

---

packages/actor-query-operation-sparql-endpoint/lib/ActorQueryOperationSparqlEndpoint.ts
packages/actor-query-operation-sparql-endpoint/test/ActorQueryOperationSparqlEndpoint-test.ts

Still needs testing and some comments
Fixes #629

IN PROGRESS: Support all operations for SPARQL endpoints

---

package.json
packages/actor-abstract-path/package.json
packages/actor-optimize-query-operation-join-bgp/package.json
packages/actor-query-operation-from-quad/package.json
packages/actor-query-operation-path-alt/package.json
packages/actor-query-operation-path-inv/package.json
packages/actor-query-operation-path-link/package.json
packages/actor-query-operation-path-nps/package.json
packages/actor-query-operation-path-one-or-more/package.json
packages/actor-query-operation-path-seq/package.json
packages/actor-query-operation-path-zero-or-more/package.json
packages/actor-query-operation-sparql-endpoint/package.json
packages/actor-rdf-resolve-hypermedia-sparql/package.json
packages/actor-rdf-resolve-quad-pattern-sparql-json/package.json
packages/actor-sparql-parse-algebra/package.json
packages/bus-optimize-query-operation/package.json
yarn.lock

Update to sparqlalgebra.js 2.2.2

---

packages/actor-query-operation-extend/package.json
packages/actor-query-operation-filter-sparqlee/package.json
packages/actor-query-operation-group/package.json
packages/actor-query-operation-leftjoin-nestedloop/package.json
packages/actor-query-operation-orderby-sparqlee/lib/ActorQueryOperationOrderBySparqlee.ts
packages/actor-query-operation-orderby-sparqlee/package.json
packages/actor-query-operation-orderby-sparqlee/test/ActorQueryOperationOrderBySparqlee-test.ts
yarn.lock

Moved to sparqlee, passing term from comunica

Issue 599 sorting of different types

---

packages/actor-init-sparql/lib/ActorInitSparql-browser.ts
packages/actor-init-sparql/test/ActorInitSparql-test.ts
packages/bus-query-operation/lib/ActorQueryOperation.ts

Add bindings() option to collect bindings generated by bindingsStream/quadStream

---

packages/actor-rdf-join-symmetrichash/lib/ActorRdfJoinSymmetricHash.ts
packages/actor-rdf-join-symmetrichash/test/ActorRdfJoinSymmetricHash-test.ts

Take value field instead of object for efficient hashfunction

---

packages/actor-abstract-path/lib/ActorAbstractPath.ts
packages/actor-abstract-path/test/ActorAbstractPath-test.ts
packages/actor-query-operation-path-nps/lib/ActorQueryOperationPathNps.ts
packages/actor-query-operation-path-one-or-more/lib/ActorQueryOperationPathOneOrMore.ts
packages/actor-query-operation-path-one-or-more/test/ActorQueryOperationPathOneOrMore-test.ts
packages/actor-query-operation-path-seq/lib/ActorQueryOperationPathSeq.ts
packages/actor-query-operation-path-seq/test/ActorQueryOperationPathSeq-test.ts
packages/actor-query-operation-path-zero-or-more/lib/ActorQueryOperationPathZeroOrMore.ts
packages/actor-query-operation-path-zero-or-more/test/ActorQueryOperationPathZeroOrMore-test.ts
packages/actor-query-operation-path-zero-or-one/lib/ActorQueryOperationPathZeroOrOne.ts
packages/actor-query-operation-path-zero-or-one/test/ActorQueryOperationPathZeroOrOne-test.ts
packages/actor-rdf-join-hash/package.json
packages/actor-rdf-join-nestedloop/package.json
packages/actor-rdf-join-symmetrichash/package.json
yarn.lock

Property paths

---

packages/actor-init-sparql/config/sets/sparql-serializers.json
packages/actor-init-sparql/lib/ActorInitSparql.ts
packages/actor-init-sparql/package.json
packages/actor-sparql-serialize-sparql-csv/README.md
packages/actor-sparql-serialize-sparql-csv/components/Actor/SparqlSerialize/SparqlCsv.jsonld
packages/actor-sparql-serialize-sparql-csv/components/components.jsonld
packages/actor-sparql-serialize-sparql-csv/components/context.jsonld
packages/actor-sparql-serialize-sparql-csv/index.ts
packages/actor-sparql-serialize-sparql-csv/lib/ActorSparqlSerializeSparqlCsv.ts
packages/actor-sparql-serialize-sparql-csv/package.json
packages/actor-sparql-serialize-sparql-csv/test/ActorSparqlSerializeSparqlCsv-test.ts
packages/actor-sparql-serialize-sparql-tsv/README.md
packages/actor-sparql-serialize-sparql-tsv/components/Actor/SparqlSerialize/SparqlTsv.jsonld
packages/actor-sparql-serialize-sparql-tsv/components/components.jsonld
packages/actor-sparql-serialize-sparql-tsv/components/context.jsonld
packages/actor-sparql-serialize-sparql-tsv/index.ts
packages/actor-sparql-serialize-sparql-tsv/lib/ActorSparqlSerializeSparqlTsv.ts
packages/actor-sparql-serialize-sparql-tsv/package.json
packages/actor-sparql-serialize-sparql-tsv/test/ActorSparqlSerializeSparqlTsv-test.ts
yarn.lock

Adds CSV and TSV SPARQL results according to the spec: https://www.w3.org/TR/2013/REC-sparql11-results-csv-tsv-20130321/
Closes #220
Note to self: update docs

Feature/serialize csv+tsv

---

packages/actor-http-native/lib/ActorHttpNative.ts
packages/actor-http-native/lib/Requester.ts
packages/actor-http-native/test/ActorHttpNative-test.ts
packages/actor-http-node-fetch/lib/ActorHttpNodeFetch.ts
packages/actor-http-node-fetch/test/ActorHttpNodeFetch-test.ts
packages/actor-init-sparql/components/Actor/Init/Sparql.jsonld
packages/actor-init-sparql/lib/ActorInitSparql.ts
packages/actor-init-sparql/test/ActorInitSparql-test.ts
packages/actor-rdf-resolve-quad-pattern-federated/lib/FederatedQuadSource.ts
packages/bus-http/lib/ActorHttp.ts
packages/bus-rdf-resolve-quad-pattern/lib/ActorRdfResolveQuadPattern.ts
packages/bus-rdf-resolve-quad-pattern/lib/ActorRdfResolveQuadPatternSource.ts
packages/bus-rdf-resolve-quad-pattern/test/ActorRdfResolveQuadPatternSource-test.ts

Feature auth http requests

---

packages/actor-rdf-dereference-http-parse/lib/ActorRdfDereferenceHttpParseBase.ts
packages/actor-rdf-dereference-http-parse/test/ActorRdfDereferenceHttpParse-test.ts

This pull request is supposed to fix the bug mentioned in issue 534.

resolve eager accept header boundary bug, fixes #534

---

packages/actor-init-sparql/lib/HttpServiceSparqlEndpoint.ts
packages/actor-init-sparql/test/HttpServiceSparqlEndpoint-test.ts

My original goal was to fix the problem where timeouts did not really kill long-running query processes (as this is not really possible in single-treaded Node).
So I solved this using the `'cluster'` API, which also allowed me to easily add support for more than one worker.
Related to #745

Enable worker threads in SPARQL endpoints

---

engines/query-sparql/test/QuerySparql-test.ts
packages/actor-init-query/lib/QueryEngineBase.ts
packages/actor-rdf-resolve-quad-pattern-federated/lib/FederatedQuadSource.ts
packages/actor-rdf-resolve-quad-pattern-federated/test/FederatedQuadSource-test.ts
packages/bus-rdf-update-quads/lib/ActorRdfUpdateQuadsDestination.ts
packages/bus-rdf-update-quads/package.json
packages/bus-rdf-update-quads/test/ActorRdfUpdateQuadsDestination-test.ts
packages/context-entries/lib/Keys.ts

Closes #911 
Something similar probably needs to be done on bus-rdf-update-hypermedia

fix: deskolemise blank nodes before updates

---

packages/mediator-combine-pipeline/README.md
packages/mediator-combine-pipeline/lib/MediatorCombinePipeline.ts
packages/mediator-combine-pipeline/test/MediatorCombinePipeline-test.ts

Supercedes #923 (rebasing to `next/major`)

feat: Order combine pipeline rebase

---

packages/actor-rdf-parse-html/test/ActorRdfParseHtml-test.ts
packages/core/lib/ActionContext.ts
packages/core/lib/Bus.ts
packages/core/test/ActionContext-test.ts
packages/core/test/Mediator-test.ts
packages/mediator-race/test/MediatorRace-test.ts
packages/runner/test/Runner-test.ts
packages/types/lib/IActionContext.ts

Developer experience improvements

---

packages/bus-rdf-update-quads/lib/ActorRdfUpdateQuadsDestination.ts

Useful internally in the reasoning components of Comunica

chore: export deskolimisation functions

---

engines/query-sparql/test/QuerySparql-test.ts
engines/query-sparql/test/assets/http/System-test-QuerySparql_3917140063/query_4174280163/simple-SPO-on-a-TPF-entrypoint_2846832685/with-results_3972485347/recording.har

Adds test coverage for SPS patterns

chore: add SPS test

---

packages/actor-http-fetch/lib/ActorHttpFetch.ts
packages/actor-http-fetch/lib/FetchInitPreprocessor-browser.ts
packages/actor-http-fetch/lib/FetchInitPreprocessor.ts
packages/actor-http-fetch/lib/IFetchInitPreprocessor.ts
packages/actor-http-fetch/package.json
packages/actor-http-fetch/test/ActorHttpFetch-test.ts
packages/actor-init-query/lib/ActorInitQueryBase.ts
packages/actor-init-query/lib/cli/CliArgsHandlerBase.ts
packages/actor-init-query/test/ActorInitQuery-test.ts
packages/context-entries/lib/Keys.ts
packages/types/lib/IQueryContext.ts

Adds the "httpTimeout" context option and implement it inside actor-http-fetch

---

engines/query-sparql-file/webpack.config.js
engines/query-sparql-rdfjs/webpack.config.js
engines/query-sparql/webpack.config.js
package.json
yarn.lock

Closes #1032
Tested using the latest Firefox, Chrome and Gnome Web.

WebPack: Avoids applying @babel/polyfill twice on the output code

---

packages/actor-rdf-parse-html/lib/ActorRdfParseHtml.ts
packages/actor-rdf-parse-html/package.json
yarn.lock

Not compatible out of the box with WebPack 5.
Not really useful (no backpressure used).

Avoids using htmlparser2 stream feature

---

packages/actor-init-query/lib/ActorInitQuery-browser.ts

I couldn't figure out a way to test the conditional I've added; suggestions are welcome. Otherwise this should be ready to publish.

Fixes browser-side unconditional override of "process" env variable (closes #1050)

---

packages/bus-rdf-resolve-quad-pattern/README.md

fix the non-working links of `bus-rdf-resolve-quad-pattern`

Fix non-working links

---

lerna.js
package.json
yarn.lock

This adds an npm-check-update script to do bulk updates across packages

chore: add npm check updates script

---

packages/actor-http-fetch/lib/ActorHttpFetch.ts
packages/actor-http-fetch/test/ActorHttpFetch-test.ts
packages/actor-init-query/lib/ActorInitQueryBase.ts
packages/actor-init-query/lib/cli/CliArgsHandlerBase.ts
packages/actor-init-query/test/ActorInitQuery-test.ts
packages/context-entries/lib/Keys.ts
packages/types/lib/IQueryContext.ts

Allow setting httpRetryCount and httpRetryDelay to ActorHttpFetch context.
Closes #1012

Add support for http retries

---

packages/actor-query-result-serialize-tree/lib/ActorQueryResultSerializeTree.ts

corrected bindingsStreamToGraphQl return type

---

packages/actor-query-result-serialize-tree/lib/index.ts
packages/actor-query-result-serialize-tree/test/ActorQueryResultSerializeTree-test.ts

fix: fix broken bindingsStreamToGraphQL export

---

engines/query-sparql-file/test/QuerySparqlFile-test.ts
engines/query-sparql-file/test/assets/dummy.jsonld
packages/actor-dereference-file/lib/ActorDereferenceFile.ts
packages/actor-dereference-file/test/ActorDereferenceFile-test.ts

Derive file url out of successfully resolved file path

---

engines/query-sparql-rdfjs/package.json

This PR should fix https://github.com/comunica/comunica/issues/1169

Fix missing dependency in query-sparql-rdfjs

---

packages/actor-init-query/lib/ActorInitQueryBase.ts
packages/actor-init-query/lib/cli/CliArgsHandlerQuery.ts
packages/actor-init-query/test/ActorInitQuery-test.ts
packages/actor-query-operation-construct/lib/ActorQueryOperationConstruct.ts
packages/actor-query-operation-construct/lib/BindingsToQuadsIterator.ts
packages/actor-query-operation-construct/package.json
packages/actor-query-operation-construct/test/BindingsToQuadsIterator-test.ts
packages/actor-query-operation-describe-subject/lib/ActorQueryOperationDescribeSubject.ts
packages/actor-query-operation-describe-subject/package.json
packages/actor-query-operation-describe-subject/test/ActorQueryOperationDescribeSubject-test.ts
packages/actor-query-operation-update-deleteinsert/lib/ActorQueryOperationUpdateDeleteInsert.ts
packages/context-entries/lib/Keys.ts
packages/types/lib/IQueryContext.ts

This PR aims to resolve https://github.com/comunica/comunica/issues/1190

remove localizeBlankNodes from context

---

engines/query-sparql-file/package.json
engines/query-sparql-rdfjs/package.json
engines/query-sparql/package.json
lerna.js

This PR aims to resolve: https://github.com/comunica/comunica/issues/1139

feat: handle engines in depcheck

---

packages/expression-evaluator/lib/aggregators/Count.ts
packages/expression-evaluator/lib/evaluators/evaluatorHelpers/BaseAggregateEvaluator.ts
packages/expression-evaluator/lib/evaluators/evaluatorHelpers/BaseExpressionEvaluator.ts
packages/expression-evaluator/lib/evaluators/evaluatorHelpers/SyncRecursiveEvaluator.ts
packages/expression-evaluator/lib/functions/Helpers.ts
packages/expression-evaluator/lib/functions/OverloadTree.ts
packages/expression-evaluator/package.json

This PR enables `sideEffect: false`. After reading https://webpack.js.org/guides/tree-shaking/ I am quite sure we can just do this. To validate my belief, I clicked through all files to make sure we don't use obvious side effect code. While checking all ts files, I also added some docs and fixed some small things webstorm didn't like.

chore: EE declare no side effects

---

packages/expression-evaluator/test/integration/functions/op.addition-test.ts
packages/expression-evaluator/test/integration/functions/op.logicalAnd-test.ts
packages/expression-evaluator/test/integration/functions/op.logicalOr-test.ts
packages/expression-evaluator/test/integration/functions/op.strlen-test.ts
packages/expression-evaluator/test/integration/misc/EBVCoercion-test.ts
packages/expression-evaluator/test/integration/misc/Exists-test.ts
packages/expression-evaluator/test/util/Aliases.ts

This PR aims to close the last issue on the sparqlee repo, being https://github.com/comunica/sparqlee/issues/35. I have made a [report of my findings](https://github.com/comunica/sparqlee/issues/35#issuecomment-1717463412) on that issue. 
If we wish to add the tests for the exists and aggregate hooks, we should do so in this PR.

test: general concepts of expression evaluator

---

package.json
packages/actor-query-operation-extend/lib/ActorQueryOperationExtend.ts
packages/expression-evaluator/test/integration/functions/op.year-test.ts

In accordance to the request made here: https://github.com/comunica/comunica/discussions/1279#discussioncomment-7301547

log expression error in extend

---

packages/actor-optimize-query-operation-assign-sources-exhaustive/lib/ActorOptimizeQueryOperationAssignSourcesExhaustive.ts

Small PR to fix: #1317
Thank you, @rubensworks !

Catch 404 of non-existing resource when fetching the selector shape

---

performance/benchmark-watdiv-file/combinations/combination_0/jbr-experiment.json
performance/benchmark-watdiv-file/combinations/combination_1/jbr-experiment.json
performance/benchmark-watdiv-file/jbr-combinations.json
performance/benchmark-watdiv-file/jbr-experiment.json.template
performance/benchmark-watdiv-file/package.json
yarn.lock

The changes here bump jbr version to the latest and update the experiment configurations accordingly for the WatDiv performance test.

Update the jbr version used in WatDiv performance test

---

packages/actor-rdf-update-quads-rdfjs-store/lib/RdfJsQuadDestination.ts
packages/actor-rdf-update-quads-rdfjs-store/package.json
yarn.lock

chore: use event-emitter-promisify

---

packages/actor-query-result-serialize-tree/lib/ActorQueryResultSerializeTree.ts
packages/actor-query-result-serialize-tree/test/ActorQueryResultSerializeTree-test.ts
packages/actor-rdf-join-minus-hash-undef/lib/ActorRdfJoinMinusHashUndef.ts
packages/actor-rdf-join-minus-hash-undef/package.json
packages/actor-rdf-join-minus-hash-undef/test/ActorRdfJoinMinusHashUndef-test.ts
packages/actor-rdf-join-minus-hash/lib/ActorRdfJoinMinusHash.ts
packages/actor-rdf-join-minus-hash/test/ActorRdfJoinMinusHash-test.ts
yarn.lock

Cleanup stream operations (unrelated to backpressure issues).

chore: cleanup stream operations

---

engines/query-sparql/test/QuerySparql-solid-test.ts
engines/query-sparql/test/QuerySparql-test.ts
packages/actor-query-result-serialize-sparql-json/lib/ActorQueryResultSerializeSparqlJson.ts
packages/actor-query-result-serialize-stats/lib/ActorQueryResultSerializeStats.ts

fix: fix stats

---

engines/query-sparql/test/Mediators-test.ts
engines/query-sparql/test/QuerySparql-test.ts
packages/actor-expression-evaluator-factory-default/lib/ExpressionEvaluator.ts
packages/bus-bindings-aggregator-factory/lib/ActorBindingsAggregatorFactory.ts
packages/bus-expression-evaluator-factory/lib/ActorExpressionEvaluatorFactory.ts
packages/bus-function-factory/lib/ActorFunctionFactory.ts
packages/bus-term-comparator-factory/lib/ActorTermComparatorFactory.ts
packages/types/lib/ExpressionEvaluator.ts

Resolve: https://github.com/comunica/comunica/pull/1442#discussion_r1787477905

Test: add new ee mediators tests

---

packages/actor-query-parse-sparql/lib/ActorQueryParseSparql.ts
packages/actor-query-parse-sparql/package.json
yarn.lock

This PR changes the usage of traqula to use the stateless parse API.

Stateless parser

---

packages/actor-http-limit-rate/lib/ActorHttpLimitRate.ts

This is a small change to fine-tune the logging in the HTTP rate limit actor, to:
1. Ensure the intervals and delays are in whole number, because with milliseconds that level of accuracy is enough. This makes the log output shorter.
2. Clarify the meaning of values printed when a request is delayed.
3. Add separate entry to signal that a host is marked for rate limiting (when not limiting by default), to make it easier to see what the rate limit kicks in.

Reduce logging verbosity in HTTP rate limit actor

---

packages/actor-query-source-identify-hypermedia/lib/StreamingStoreMetadata.ts
packages/actor-query-source-identify-hypermedia/package.json
packages/actor-query-source-identify-hypermedia/test/QuerySourceHypermedia-test.ts
packages/types/lib/IAggregatedStore.ts
yarn.lock

aggregate store ending reporting mechanism
